[env]
PORT = "8000"

[config]
skip_core_tasks = true

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.watch]
description = "Watch files and recompile the project on change"
run_task = [
    { name = "build_web" },
]
watch = true

[tasks.serve]
description = "Start server"
install_crate = { crate_name = "microserver", binary = "microserver", test_arg = "-h" }
command = "microserver"
args = ["--port", "${PORT}", "web"]

[tasks.copy_web_src]
script = '''
mkdir -p web
cp -r web_src/ web/
'''

[tasks.build_web]
description = "Build with wasm-pack"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
script = '''
wasm-pack build --target web --out-name app --dev
cp pkg/app_bg.wasm web/
cp pkg/app.js web/
'''
dependencies = ["copy_web_src"]

[tasks.build_web_release]
description = "Build with wasm-pack in release mode"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
script = '''
wasm-pack build --target web --out-name app
cp pkg/app_bg.wasm web/
cp pkg/app.js web/
'''
dependencies = ["copy_web_src"]

# separate wasm-opt task since wasm-pack can't currently do wasm-opt on an M1 mac
[tasks.build_web_release_optimized]
command = "wasm-opt"
args = ["pkg/app_bg.wasm", "-Os", "--fast-math", "-o", "web/app_bg.wasm"]
dependencies = ["build_web_release"]