[package]
authors = ["joel nises <joel.nises@gmail.com>"]
edition = "2021"
name = "synth"
version = "0.0.1"

[dependencies]
biquad = "0.4.2"
crossbeam = "0.8"
egui = "0.17"
glam = "0.20"
wmidi = "4.0"
once_cell = "1.10"
static_assertions = "1.1.0"